source 'https://rubygems.org'
# gem 'github-pages', group: :jekyll_plugins
gem 'activesupport'
gem 'mini_racer'
# gem 'github-pages-health-check'
gem 'html-proofer', group: :development
gem 'jekyll', '~> 3.8.5'
group :jekyll_plugins do
  gem 'jekyll-avatar'
  gem 'jekyll-coffeescript'
  gem 'jekyll-commonmark-ghpages'
  gem 'jekyll-default-layout'
  gem 'jekyll-feed'
  gem 'jekyll-gist'
  gem 'jekyll-github-metadata'
  # gem 'jekyll-mentions'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-paginate'
  gem 'jekyll-readme-index'
  gem 'jekyll-redirect-from'
  gem 'jekyll-relative-links'
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-titles-from-headings'
  gem 'jemoji'
end
# themes
gem 'jekyll-swiss'
gem 'jekyll-theme-architect'
gem 'jekyll-theme-cayman'
gem 'jekyll-theme-dinky'
gem 'jekyll-theme-hacker'
gem 'jekyll-theme-leap-day'
gem 'jekyll-theme-merlot'
gem 'jekyll-theme-midnight'
gem 'jekyll-theme-minimal'
gem 'jekyll-theme-modernist'
gem 'jekyll-theme-primer'
gem 'jekyll-theme-slate'
gem 'jekyll-theme-tactile'
gem 'jekyll-theme-time-machine'
gem 'minima'
# end themes
gem 'kramdown'
gem 'liquid'
gem 'listen'
gem 'mercenary'
gem 'rack', '~> 2.0.6'
gem 'rouge'
gem 'rubocop'
gem 'rubyzip', '~> 1.2.2'
# gem 'ruby-oembed'
gem 'terminal-table'
